MOUSEKEY_ENABLE = no     # Mouse keys
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
ENABLE_VIA = no
MIDI_ENABLE	= no
UNICODE_ENABLE = no
BLUETOOTH_ENABLE = no
AUDIO_ENABLE = no
SWAP_HANDS_ENABLE = no
RGBLIGHT_ENABLE = yes    # Enable WS2812 RGB underlight.
OLED_ENABLE     = yes
OLED_DRIVER     = ssd1306
LTO_ENABLE      = yes
WPM_ENABLE		= yes
# TAP DANCE
TAP_DANCE_ENABLE = yes
# CAPS WORDS
CAPS_WORD_ENABLE = yes
# OPTIMIZATION
EXTRAFLAGS += -flto
# KEY OVERRIDE
KEY_OVERRIDE_ENABLE = yes
